name: Build exe, deb

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: app

    - uses: actions/upload-artifact@v4
      with:
        name: Simplex_Method
        path: app/dist/windows

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: app

      - uses: actions/upload-artifact@v4
        with:
          name: Simplex_Method
          path: app/dist/linux