name: Build cross platform

on:
  push:
    tags:
      - 'b*'
      - 'v*'

jobs:
  create-release:
    name: Create release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ['ubuntu-latest']
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}

  build-win:
    name: Windows build
    needs: create-release
    runs-on: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - run: pip install -r ./app/requirements.txt pyinstaller
    - run: pyinstaller --onefile --windowed --name "Simplex_Method" --icon=app/icons/solution.ico --add-data=app/icons/*.ico:icons app/main.py
    - uses: actions/upload-artifact@v4
      with:
        path: dist/Simplex_Method.exe
        name: Simplex_Method_windows

    - name: Upload release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.release_url }}
        asset_path: dist/Simplex_Method.exe
        asset_name: Simplex_Method.exe
        asset_content_type: application/exe

  build-lin:
    name: Ubuntu build
    needs: create-release
    runs-on: [ 'ubuntu-latest' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install -r ./app/requirements.txt pyinstaller
      - run: pyinstaller --onefile --windowed --name "Simplex_Method" --icon=app/icons/solution.ico --add-data=app/icons/*.ico:icons app/main.py
      - uses: actions/upload-artifact@v4
        with:
          path: dist/Simplex_Method
          name: Simplex_Method_linux

      - name: Upload release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: dist/Simplex_Method
          asset_name: Simplex_Method_Linux.bin
          asset_content_type: application/bin

  build-mac:
    name: MacOS build
    needs: create-release
    runs-on: ['macos-latest']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install -r ./app/requirements.txt pyinstaller pillow
      - run: pyinstaller --onefile --windowed --name "Simplex_Method" --icon=app/icons/solution.ico --add-data=app/icons/*.ico:icons app/main.py
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
          name: Simplex_Method_macos

      - name: Upload release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: dist/Simplex_Method
          asset_name: SimplexMethodMacOS.bin
          asset_content_type: application/bin