name: Build cross platform

on:
  push:
    tags:
      - 'b*'

jobs:
  build-win:
    runs-on: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - run: pip install -r ./app/requirements.txt pyinstaller
    - run: pyinstaller --onefile --windowed --name "Simplex_Method" --icon=app/icons/solution.ico --add-data=app/icons/*.ico:icons app/main.py
    - uses: actions/upload-artifact@v4
      with:
        path: dist/Simplex_Method.exe
        name: Simplex_Method_win

  build-lin:
    runs-on: [ 'ubuntu-latest' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - run: pip install -r ./app/requirements.txt pyinstaller
      - run: pyinstaller --onefile --windowed --name "Simplex_Method" --icon=app/icons/solution.ico --add-data=app/icons/*.ico:icons app/main.py
      - uses: actions/upload-artifact@v4
        with:
          path: dist/Simplex_Method
          name: Simplex_Method_lin

  build-mac:
    runs-on: ['macos-latest']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - run: pip install -r ./app/requirements.txt pyinstaller pillow
      - run: pyinstaller --onefile --windowed --name "Simplex_Method" --icon=app/icons/solution.ico --add-data=app/icons/*.ico:icons app/main.py
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
          name: macos